return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 40,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 7,
  nextobjectid = 38,
  properties = {
    ["name"] = "Chapter 1 - room_field_puzzle1",
    ["border"] = "simple",
    ["keepmusic"] = true
  },
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 1,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 120,
          width = 40.0,
          height = 160.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 120,
          width = 480.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 160,
          width = 40.0,
          height = 120.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1320,
          y = 240,
          width = 280.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 360,
          width = 320.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 400,
          width = 320.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 360,
          width = 440.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 360,
          width = 280.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 400,
          width = 240.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 240,
          width = 400.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 240,
          width = 240.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 200,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 160,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 120,
          width = 240.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 160,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 200,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects_ground",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "ch1_room_art",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["texture"] = "world/ch1_dark/rooms/room_field_puzzle1"
          }
        },
        {
          id = 15,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 280,
          width = 960.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 24.0,
            ["rows"] = 2.0,
            ["frames"] = 9
          }
        },
        {
          id = 16,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 1440,
          y = 280,
          width = 200.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 5.0,
            ["rows"] = 2.0,
            ["frames"] = 9
          }
        },
        {
          id = 17,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 360,
          width = 240.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 6.0,
            ["rows"] = 1.0,
            ["frames"] = 9
          }
        },
        {
          id = 18,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 200,
          width = 320.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 8.0,
            ["rows"] = 2.0,
            ["frames"] = 9
          }
        },
        {
          id = 19,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 160,
          width = 240.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 6.0,
            ["rows"] = 1.0,
            ["frames"] = 9
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "event_spawn",
          type = "",
          shape = "point",
          x = 100,
          y = 356,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "marker_a",
          type = "",
          shape = "point",
          x = 100,
          y = 336,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "marker_b",
          type = "",
          shape = "point",
          x = 1500,
          y = 336,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "enemycollision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 280,
          width = 40.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 280,
          width = 40.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {

      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "ch1_glow_controller",
          type = "",
          shape = "rectangle",
          x = 1160,
          y = 80,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["puzzle"] = "room_field_puzzle1",
            ["tile_count"] = 3
          }
        },
        {
          id = 4,
          name = "ch1_glow_tile",
          type = "",
          shape = "rectangle",
          x = 1110,
          y = 280,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["puzzle"] = "room_field_puzzle1",
            ["index"] = 101347
          }
        },
        {
          id = 5,
          name = "ch1_glow_tile",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["puzzle"] = "room_field_puzzle1",
            ["index"] = 101348
          }
        },
        {
          id = 6,
          name = "ch1_glow_tile",
          type = "",
          shape = "rectangle",
          x = 1170,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["puzzle"] = "room_field_puzzle1",
            ["index"] = 101349
          }
        },
        {
          id = 7,
          name = "ch1_readable",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 120,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text"] = "* Check the clock.[wait:5]\n* In order to solve this puzzle,[wait:5] you'll have to hurry."
          }
        },
        {
          id = 29,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = -10,
          y = 280,
          width = 20.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "room_field_topchef",
            ["marker"] = "marker_b",
            ["facing"] = "left"
          }
        },
        {
          id = 31,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 1590,
          y = 280,
          width = 20.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "room_field_maze",
            ["marker"] = "marker_a",
            ["facing"] = "right"
          }
        },
        {
          id = 35,
          name = "ch1_enemy",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 160,
          width = 70,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["encounter"] = "ch1_rudinn",
            ["defeated_flag"] = "ch1_enemy_room_field_puzzle1_101325"
          }
        },
        {
          id = 36,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 90,
          width = 68,
          height = 60,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_puzzlepiece",
            ["frames"] = 2,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2,
            ["scale_y"] = 2,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = "* The Darkner looks at you expectantly."
          }
        },
        {
          id = 37,
          name = "ch1_glow_gate",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 280,
          width = 120,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["puzzle"] = "room_field_puzzle1"
          }
        }
      }
    }
  }
}
