return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 7,
  nextobjectid = 26,
  properties = {
    ["name"] = "Chapter 1 - room_field_puzzletutorial",
    ["border"] = "simple",
    ["keepmusic"] = true
  },
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 1,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 80,
          width = 40.0,
          height = 360.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 400,
          width = 400.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 280,
          width = 40.0,
          height = 120.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 280,
          width = 120.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 160,
          width = 164.10256,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 120,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 80,
          width = 200.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 80,
          width = 200.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 120,
          width = 60.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 360,
          width = 80.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 360,
          width = 80.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects_ground",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "ch1_room_art",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["texture"] = "world/ch1_dark/rooms/room_field_puzzletutorial"
          }
        },
        {
          id = 23,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 120,
          width = 360.0,
          height = 240.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 9.0,
            ["rows"] = 6.0,
            ["frames"] = 9
          }
        },
        {
          id = 24,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 200,
          width = 160.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 4.0,
            ["rows"] = 2.0,
            ["frames"] = 9
          }
        },
        {
          id = 25,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 360,
          width = 200.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 5.0,
            ["rows"] = 1.0,
            ["frames"] = 9
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "event_spawn",
          type = "",
          shape = "point",
          x = 319,
          y = 296,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "marker_a",
          type = "",
          shape = "point",
          x = 540,
          y = 276,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "enemycollision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {

      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {

      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 11,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 620,
          y = 200,
          width = 20.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "room_field_shop1",
            ["marker"] = "marker_b",
            ["facing"] = "right"
          }
        },
        {
          id = 13,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 388,
          y = 96,
          width = 68,
          height = 60,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_puzzlepiece",
            ["frames"] = 2,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2,
            ["scale_y"] = 2,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = "* The Darkner looks at you expectantly."
          }
        },
        {
          id = 14,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_sign",
            ["frames"] = 1,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2,
            ["scale_y"] = 2,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = {"* \"Hole Goals\"", "$1 - Monthly tutorial,[wait:5] weekly.\n$10 - Weekly tutorial,[wait:5] monthly.\n$100 - Stop making tutorials."}
          }
        },
        {
          id = 16,
          name = "ch1_readable",
          type = "",
          shape = "rectangle",
          x = 290,
          y = 120,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["action"] = "donation_hole"
          }
        },
        {
          id = 17,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 220,
          y = 320,
          width = 68.0,
          height = 60.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_puzzlepiece",
            ["frames"] = 2,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = "* The Darkner looks at you expectantly."
          }
        },
        {
          id = 18,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 320,
          width = 68.0,
          height = 60.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_puzzlepiece",
            ["frames"] = 2,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = "* The Darkner looks at you expectantly."
          }
        },
        {
          id = 19,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 290,
          width = 68.0,
          height = 60.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_puzzlepiece",
            ["frames"] = 2,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = "* The Darkner looks at you expectantly."
          }
        },
        {
          id = 20,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 130,
          y = 290,
          width = 68.0,
          height = 60.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_puzzlepiece",
            ["frames"] = 2,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = "* The Darkner looks at you expectantly."
          }
        }
      }
    }
  }
}
