return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 50,
  height = 17,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 7,
  nextobjectid = 44,
  properties = {
    ["name"] = "Chapter 1 - room_field2",
    ["border"] = "simple",
    ["keepmusic"] = true
  },
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 1,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1160,
          y = 280,
          width = 80.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1240,
          y = 240,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 200,
          width = 400.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1680,
          y = 240,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1720,
          y = 280,
          width = 280.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1160,
          y = 400,
          width = 80.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1240,
          y = 440,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 480,
          width = 400.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1680,
          y = 440,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1720,
          y = 400,
          width = 280.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 0,
          width = 40.0,
          height = 280.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 0,
          width = 40.0,
          height = 280.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 240,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 240,
          width = 40.0,
          height = 240.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 440,
          width = 480.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 480,
          width = 40.0,
          height = 200.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 440,
          width = 40.0,
          height = 240.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 440,
          width = 360.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 240,
          width = 160.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 200,
          width = 440.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 240,
          width = 280.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects_ground",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "ch1_room_art",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["texture"] = "world/ch1_dark/rooms/room_field2"
          }
        },
        {
          id = 22,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 0,
          width = 80.0,
          height = 287.17948,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 2.0,
            ["rows"] = 7.179487,
            ["frames"] = 9
          }
        },
        {
          id = 23,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 280,
          width = 1000.0,
          height = 160.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 25.0,
            ["rows"] = 4.0,
            ["frames"] = 9
          }
        },
        {
          id = 24,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 240,
          width = 360.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 9.0,
            ["rows"] = 1.0,
            ["frames"] = 9
          }
        },
        {
          id = 25,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 440,
          width = 120.0,
          height = 240.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 3.0,
            ["rows"] = 6.0,
            ["frames"] = 9
          }
        },
        {
          id = 26,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 1160,
          y = 320,
          width = 840.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 21.0,
            ["rows"] = 2.0,
            ["frames"] = 9
          }
        },
        {
          id = 27,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 240,
          width = 400.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 10.0,
            ["rows"] = 1.0,
            ["frames"] = 9
          }
        },
        {
          id = 28,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 1240,
          y = 280,
          width = 480.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 12.0,
            ["rows"] = 1.0,
            ["frames"] = 9
          }
        },
        {
          id = 29,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 1240,
          y = 400,
          width = 480.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 12.0,
            ["rows"] = 1.0,
            ["frames"] = 9
          }
        },
        {
          id = 30,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 440,
          width = 400.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 10.0,
            ["rows"] = 1.0,
            ["frames"] = 9
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "event_spawn",
          type = "",
          shape = "point",
          x = 299,
          y = 356,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "marker_d",
          type = "",
          shape = "point",
          x = 1900,
          y = 376,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "marker_a",
          type = "",
          shape = "point",
          x = 279,
          y = 100,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "marker_b",
          type = "",
          shape = "point",
          x = 689,
          y = 580,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "enemycollision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1200,
          y = 320,
          width = 40.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1720,
          y = 320,
          width = 40.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {

      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 610,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_sign",
            ["frames"] = 1,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2,
            ["scale_y"] = 2,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = "* (Hey,[wait:5] don't read this sign! It's a work in progress!)\n* (SIGNED, LANCER)"
          }
        },
        {
          id = 4,
          name = "ch1_enemy",
          type = "",
          shape = "rectangle",
          x = 1420,
          y = 280,
          width = 70,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["encounter"] = "ch1_rudinn_duo",
            ["defeated_flag"] = "ch1_enemy_room_field2_101248"
          }
        },
        {
          id = 15,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 240,
          y = -10,
          width = 80.0,
          height = 20.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "room_field1",
            ["marker"] = "marker_b",
            ["facing"] = "up"
          }
        },
        {
          id = 16,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 670,
          width = 120.0,
          height = 20.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "room_field2A",
            ["marker"] = "marker_a",
            ["facing"] = "down"
          }
        },
        {
          id = 17,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 1990,
          y = 320,
          width = 20.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "room_field_topchef",
            ["marker"] = "marker_c",
            ["facing"] = "right"
          }
        },
        {
          id = 19,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 670,
          y = 280,
          width = 72,
          height = 70,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_lancer_dt",
            ["frames"] = 1,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2,
            ["scale_y"] = 2,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["action"] = "field2_lancer"
          }
        }
      }
    }
  }
}
