return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 91,
  height = 13,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 7,
  nextobjectid = 51,
  properties = {
    ["name"] = "Chapter 1 - room_dark2",
    ["border"] = "simple",
    ["music"] = "creepylandscape"
  },
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 1,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 280,
          width = 280.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 320,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 360,
          width = 520.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 400,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 440,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 480,
          width = 760.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 160,
          width = 360.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 200,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 240,
          width = 520.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 280,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 320,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 360,
          width = 600.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1560,
          y = 440,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1560,
          y = 400,
          width = 240.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1760,
          y = 360,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1760,
          y = 320,
          width = 400.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2120,
          y = 360,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2120,
          y = 400,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2160,
          y = 400,
          width = 440.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1440,
          y = 320,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1480,
          y = 280,
          width = 200.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1640,
          y = 240,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1680,
          y = 200,
          width = 560.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2240,
          y = 240,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2240,
          y = 280,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2240,
          y = 280,
          width = 440.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2680,
          y = 320,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2600,
          y = 440,
          width = 640.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2680,
          y = 360,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2680,
          y = 360,
          width = 480.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3240,
          y = 400,
          width = 400.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3120,
          y = 320,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3120,
          y = 360,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3160,
          y = 280,
          width = 480.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects_ground",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "ch1_room_art",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["texture"] = "world/ch1_dark/rooms/room_dark2"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "event_spawn",
          type = "",
          shape = "point",
          x = 100,
          y = 276,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "marker_a",
          type = "",
          shape = "point",
          x = 100,
          y = 256,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "marker_b",
          type = "",
          shape = "point",
          x = 3540,
          y = 366,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "enemycollision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {

      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {

      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 1100,
          y = 186,
          width = 78,
          height = 74,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_wobblything",
            ["frames"] = 4,
            ["animation_speed"] = 0.17,
            ["trigger"] = "near_x",
            ["sound"] = "ch1_dark/wobbler",
            ["scale_x"] = 2,
            ["scale_y"] = 2,
            ["origin_x"] = 10,
            ["origin_y"] = 5
          }
        },
        {
          id = 16,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = -10,
          y = 200,
          width = 20.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "room_dark1a",
            ["marker"] = "marker_b",
            ["facing"] = "left"
          }
        },
        {
          id = 18,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 2300,
          y = 42,
          width = 78,
          height = 74,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_wobblything",
            ["frames"] = 4,
            ["animation_speed"] = 0.17,
            ["trigger"] = "near_x",
            ["sound"] = "ch1_dark/wobbler",
            ["scale_x"] = 2,
            ["scale_y"] = 2,
            ["origin_x"] = 10,
            ["origin_y"] = 5
          }
        },
        {
          id = 19,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 2448,
          y = 38,
          width = 78,
          height = 74,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_wobblything",
            ["frames"] = 4,
            ["animation_speed"] = 0.17,
            ["trigger"] = "near_x",
            ["sound"] = "ch1_dark/wobbler",
            ["scale_x"] = 2,
            ["scale_y"] = 2,
            ["origin_x"] = 10,
            ["origin_y"] = 5
          }
        },
        {
          id = 38,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 1388,
          y = 122,
          width = 78,
          height = 74,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_wobblything",
            ["frames"] = 4,
            ["animation_speed"] = 0.17,
            ["trigger"] = "near_x",
            ["sound"] = "ch1_dark/wobbler",
            ["scale_x"] = 2,
            ["scale_y"] = 2,
            ["origin_x"] = 10,
            ["origin_y"] = 5
          }
        },
        {
          id = 39,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 2868,
          y = 68,
          width = 72,
          height = 68,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_darklancer",
            ["frames"] = 2,
            ["animation_speed"] = 0.17,
            ["trigger"] = "lancer_up",
            ["motion"] = "up",
            ["motion_speed"] = 240,
            ["scale_x"] = 2,
            ["scale_y"] = 2
          }
        },
        {
          id = 44,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 3248,
          y = 42,
          width = 78,
          height = 74,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_wobblything",
            ["frames"] = 4,
            ["animation_speed"] = 0.17,
            ["trigger"] = "near_x",
            ["sound"] = "ch1_dark/wobbler",
            ["scale_x"] = 2,
            ["scale_y"] = 2,
            ["origin_x"] = 10,
            ["origin_y"] = 5
          }
        },
        {
          id = 45,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 3486,
          y = 42,
          width = 78,
          height = 74,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_wobblything",
            ["frames"] = 4,
            ["animation_speed"] = 0.17,
            ["trigger"] = "near_x",
            ["sound"] = "ch1_dark/wobbler",
            ["scale_x"] = 2,
            ["scale_y"] = 2,
            ["origin_x"] = 10,
            ["origin_y"] = 5
          }
        },
        {
          id = 46,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 3630,
          y = 320,
          width = 26.0,
          height = 78.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "room_dark3",
            ["marker"] = "marker_a",
            ["facing"] = "right"
          }
        },
        {
          id = 48,
          name = "ch1_readable",
          type = "",
          shape = "rectangle",
          x = 2370,
          y = 280,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text"] = "* (It's too dark to see anything.)"
          }
        },
        {
          id = 49,
          name = "ch1_readable",
          type = "",
          shape = "rectangle",
          x = 2780,
          y = 360,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text"] = "* (It's too dark to see anything.)"
          }
        },
        {
          id = 50,
          name = "ch1_readable",
          type = "",
          shape = "rectangle",
          x = 3010,
          y = 360,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text"] = "* (It's too dark to see anything.)"
          }
        }
      }
    }
  }
}
