return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 25,
  height = 25,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 7,
  nextobjectid = 24,
  properties = {
    ["name"] = "Chapter 1 - room_castle_front",
    ["border"] = "simple",
    ["keepmusic"] = true
  },
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 1,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 280,
          width = 40.0,
          height = 360.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 640,
          width = 160.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 680,
          width = 40.0,
          height = 120.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 760,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 760,
          width = 40.0,
          height = 240.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 760,
          width = 40.0,
          height = 240.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 760,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 640,
          width = 40.0,
          height = 160.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 640,
          width = 120.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 280,
          width = 40.0,
          height = 400.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 280,
          width = 640.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects_ground",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "ch1_room_art",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["texture"] = "world/ch1_dark/rooms/room_castle_front"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "event_spawn",
          type = "",
          shape = "point",
          x = 523,
          y = 576,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "marker_a",
          type = "",
          shape = "point",
          x = 519,
          y = 900,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "enemycollision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {

      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {

      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "ch1_trigger",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["trigger"] = "castle_front",
            ["flag"] = "ch1_castle_prophecy_v4",
            ["auto"] = true
          }
        },
        {
          id = 15,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 990,
          width = 160.0,
          height = 30.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "room_castle_town",
            ["marker"] = "marker_b",
            ["facing"] = "down"
          }
        },
        {
          id = 17,
          name = "ch1_readable",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 260,
          width = 80.0,
          height = 60.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text"] = {"* Hey,[wait:5] Kris,[wait:5] I really think we should catch up with Susie.", "* We can come back here after our adventure is over...", "* ... and then I can bake you a yummy cake!"},
            ["repeat_text"] = {"* Kris,[wait:5] perhaps we should save the world first...?", "* It seems a bit important."},
            ["flag"] = "ch1_read_castle_front_door"
          }
        },
        {
          id = 18,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 305,
          y = 204,
          width = 30.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_castle_torch",
            ["frames"] = 6,
            ["start_frame"] = 0,
            ["animation_speed"] = 0.17,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 19,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 420,
          y = 204,
          width = 30.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_castle_torch",
            ["frames"] = 6,
            ["start_frame"] = 0,
            ["animation_speed"] = 0.17,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 20,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 204,
          width = 30.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_castle_torch",
            ["frames"] = 6,
            ["start_frame"] = 0,
            ["animation_speed"] = 0.17,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 21,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 204,
          width = 30.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_castle_torch",
            ["frames"] = 6,
            ["start_frame"] = 0,
            ["animation_speed"] = 0.17,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 22,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 308,
          y = 40,
          width = 30.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_castle_torch",
            ["frames"] = 6,
            ["start_frame"] = 0,
            ["animation_speed"] = 0.17,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 23,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 40,
          width = 30.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_castle_torch",
            ["frames"] = 6,
            ["start_frame"] = 0,
            ["animation_speed"] = 0.17,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        }
      }
    }
  }
}
