return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 29,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 7,
  nextobjectid = 54,
  properties = {
    ["name"] = "Chapter 1 - room_castle_town",
    ["border"] = "simple",
    ["music"] = "castletown_empty"
  },
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 1,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2,
          y = 1114,
          width = 656.4104,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = -100,
          y = 920,
          width = 290.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 920,
          width = 190.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6,
          y = 1052,
          width = 188.0,
          height = 90.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 446,
          y = 1052,
          width = 192.0,
          height = 100.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = -2,
          y = 832,
          width = 194.0,
          height = 126.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 832,
          width = 194.0,
          height = 118.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6,
          y = 222,
          width = 160.0,
          height = 204.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 94,
          y = 420,
          width = 30.0,
          height = 420.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 516,
          y = 374,
          width = 48.0,
          height = 458.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 476,
          y = 204,
          width = 86.0,
          height = 218.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 182,
          y = 204,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 200,
          width = 24.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 236,
          y = 196,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 362,
          y = 194,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 396,
          y = 198,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 424,
          y = 206,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 414,
          y = 202,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 236,
          y = 164,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 362,
          y = 162,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 110,
          y = 734,
          width = 126.0,
          height = 42.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 398,
          y = 738,
          width = 124.0,
          height = 38.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 124,
          y = 578,
          width = 114.0,
          height = 42.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 398,
          y = 582,
          width = 118.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects_ground",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "ch1_room_art",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["texture"] = "world/ch1_dark/rooms/room_castle_town"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "event_spawn",
          type = "",
          shape = "point",
          x = 319,
          y = 396,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "marker_a",
          type = "",
          shape = "point",
          x = 100,
          y = 1016,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "marker_b",
          type = "",
          shape = "point",
          x = 321,
          y = 276,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "marker_x",
          type = "",
          shape = "point",
          x = 540,
          y = 1018,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "enemycollision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {

      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {

      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "savepoint",
          type = "",
          shape = "rectangle",
          x = 298,
          y = 290,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text"] = {"* At times,[wait:5] you see it flickering.\n* The light only you can see.", "* By second nature,[wait:5] you reach out,[wait:5] and..."}
          }
        },
        {
          id = 4,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = -10,
          y = 958,
          width = 22.0,
          height = 101.05261999999999,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "room_castle_outskirts",
            ["marker"] = "marker_b",
            ["facing"] = "left"
          }
        },
        {
          id = 9,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 246,
          y = 192,
          width = 140.0,
          height = 20.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "room_castle_front",
            ["marker"] = "marker_a",
            ["facing"] = "up"
          }
        },
        {
          id = 11,
          name = "ch1_susie_npc",
          type = "",
          shape = "rectangle",
          x = 394,
          y = 948,
          width = 52,
          height = 92,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 296,
          y = 0,
          width = 46.0,
          height = 128.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_castle_fountain",
            ["frames"] = 6,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 13,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 630,
          y = 954,
          width = 18.0,
          height = 103.1579,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "room_castle_tutorial",
            ["marker"] = "marker_x",
            ["facing"] = "right"
          }
        },
        {
          id = 23,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 122,
          y = 426,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_sul",
            ["frames"] = 1,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 24,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 478,
          y = 420,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_sur_dark",
            ["frames"] = 1,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 1.0,
            ["scale_y"] = 1.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 25,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 436,
          y = 246,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_sur_dark",
            ["frames"] = 1,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 1.0,
            ["scale_y"] = 1.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 26,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 166,
          y = 246,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_sul",
            ["frames"] = 1,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 36,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 38,
          y = 568,
          width = 30.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_castle_torch",
            ["frames"] = 6,
            ["start_frame"] = 0,
            ["animation_speed"] = 0.17,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 37,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 572,
          y = 568,
          width = 30.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_castle_torch",
            ["frames"] = 6,
            ["start_frame"] = 0,
            ["animation_speed"] = 0.17,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 38,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 876,
          width = 30.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_castle_torch",
            ["frames"] = 6,
            ["start_frame"] = 0,
            ["animation_speed"] = 0.17,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 39,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 876,
          width = 30.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_castle_torch",
            ["frames"] = 6,
            ["start_frame"] = 0,
            ["animation_speed"] = 0.17,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 40,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 466,
          y = 876,
          width = 30.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_castle_torch",
            ["frames"] = 6,
            ["start_frame"] = 0,
            ["animation_speed"] = 0.17,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 41,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 594,
          y = 876,
          width = 30.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_castle_torch",
            ["frames"] = 6,
            ["start_frame"] = 0,
            ["animation_speed"] = 0.17,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 42,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 612,
          width = 158.0,
          height = 166.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_castle_shop",
            ["frames"] = 4,
            ["start_frame"] = 2,
            ["animation_speed"] = 0,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 43,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 366,
          y = 612,
          width = 158.0,
          height = 166.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_castle_shop",
            ["frames"] = 4,
            ["start_frame"] = 3,
            ["animation_speed"] = 0,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 44,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 124,
          y = 458,
          width = 158.0,
          height = 166.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_castle_shop",
            ["frames"] = 4,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 45,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 370,
          y = 460,
          width = 158.0,
          height = 166.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_castle_shop",
            ["frames"] = 4,
            ["start_frame"] = 1,
            ["animation_speed"] = 0,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0
          }
        },
        {
          id = 50,
          name = "ch1_readable",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 582,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text"] = "* (It looks like a shop,[wait:5] but the door is locked,[wait:5] and no one's inside...)",
            ["repeat_text"] = "* (It's locked.)",
            ["flag"] = "ch1_read_castle_town_door"
          }
        },
        {
          id = 51,
          name = "ch1_readable",
          type = "",
          shape = "rectangle",
          x = 156,
          y = 732,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text"] = "* (It looks like a shop,[wait:5] but the door is locked,[wait:5] and no one's inside...)",
            ["repeat_text"] = "* (It's locked.)",
            ["flag"] = "ch1_read_castle_town_door"
          }
        },
        {
          id = 52,
          name = "ch1_readable",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 740,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text"] = "* (It looks like a shop,[wait:5] but the door is locked,[wait:5] and no one's inside...)",
            ["repeat_text"] = "* (It's locked.)",
            ["flag"] = "ch1_read_castle_town_door"
          }
        },
        {
          id = 53,
          name = "ch1_readable",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 584,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text"] = "* (It looks like a shop,[wait:5] but the door is locked,[wait:5] and no one's inside...)",
            ["repeat_text"] = "* (It's locked.)",
            ["flag"] = "ch1_read_castle_town_door"
          }
        }
      }
    }
  }
}
