return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 49,
  height = 37,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 7,
  nextobjectid = 79,
  properties = {
    ["name"] = "Chapter 1 - room_field_maze",
    ["border"] = "simple",
    ["keepmusic"] = true
  },
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 1,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 360,
          width = 200.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 160,
          width = 40.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 240,
          width = 200.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 160,
          width = 40.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 120,
          width = 240.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 400,
          width = 240.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 240,
          width = 240.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 280,
          width = 40.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 320,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 240,
          width = 40.0,
          height = 120.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 240,
          width = 240.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1000,
          y = 280,
          width = 40.0,
          height = 240.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 360,
          width = 120.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 400,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 440,
          width = 280.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 480,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 520,
          width = 80.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 520,
          width = 80.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 560,
          width = 40.0,
          height = 120.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 560,
          width = 40.0,
          height = 120.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1000,
          y = 800,
          width = 40.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 880,
          width = 40.0,
          height = 280.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 880,
          width = 40.0,
          height = 280.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 1120,
          width = 360.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 1160,
          width = 40.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 1240,
          width = 840.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1320,
          y = 1280,
          width = 440.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1680,
          y = 1240,
          width = 280.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1680,
          y = 1120,
          width = 280.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1320,
          y = 1080,
          width = 369.23076000000003,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 1120,
          width = 360.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 880,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 800,
          width = 40.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 880,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 680,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 640,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 640,
          width = 40.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 680,
          width = 360.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 800,
          width = 520.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 480,
          width = 40.0,
          height = 320.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 480,
          width = 40.0,
          height = 200.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1000,
          y = 680,
          width = 520.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 800,
          width = 480.0,
          height = 40.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1480,
          y = 720,
          width = 40.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects_ground",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "ch1_room_art",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["texture"] = "world/ch1_dark/rooms/room_field_maze"
          }
        },
        {
          id = 3,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 280,
          width = 200.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 5.0,
            ["rows"] = 2.0,
            ["frames"] = 9
          }
        },
        {
          id = 4,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 160,
          width = 240.0,
          height = 240.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 6.0,
            ["rows"] = 6.0,
            ["frames"] = 9
          }
        },
        {
          id = 21,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 280,
          width = 200.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 5.0,
            ["rows"] = 2.0,
            ["frames"] = 9
          }
        },
        {
          id = 22,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 360,
          width = 200.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 5.0,
            ["rows"] = 2.0,
            ["frames"] = 9
          }
        },
        {
          id = 23,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 280,
          width = 240.0,
          height = 240.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 6.0,
            ["rows"] = 6.0,
            ["frames"] = 9
          }
        },
        {
          id = 24,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 520,
          width = 80.0,
          height = 160.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 2.0,
            ["rows"] = 4.0,
            ["frames"] = 9
          }
        },
        {
          id = 25,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 680,
          width = 240.0,
          height = 200.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 6.0,
            ["rows"] = 5.0,
            ["frames"] = 9
          }
        },
        {
          id = 26,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 720,
          width = 520.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 13.0,
            ["rows"] = 2.0,
            ["frames"] = 9
          }
        },
        {
          id = 27,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 480,
          width = 120.0,
          height = 240.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 3.0,
            ["rows"] = 6.0,
            ["frames"] = 9
          }
        },
        {
          id = 28,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 880,
          width = 80.0,
          height = 280.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 2.0,
            ["rows"] = 7.0,
            ["frames"] = 9
          }
        },
        {
          id = 29,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 1160,
          width = 800.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 20.0,
            ["rows"] = 2.0,
            ["frames"] = 9
          }
        },
        {
          id = 30,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 1320,
          y = 1120,
          width = 360.0,
          height = 160.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 9.0,
            ["rows"] = 4.0,
            ["frames"] = 9
          }
        },
        {
          id = 31,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 1680,
          y = 1160,
          width = 280.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 7.0,
            ["rows"] = 2.0,
            ["frames"] = 9
          }
        },
        {
          id = 70,
          name = "ch1_grass",
          type = "",
          shape = "rectangle",
          x = 1000,
          y = 720,
          width = 480.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["columns"] = 12.0,
            ["rows"] = 2.0,
            ["frames"] = 9
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "event_spawn",
          type = "",
          shape = "point",
          x = 299,
          y = 316,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "marker_b",
          type = "",
          shape = "point",
          x = 1860,
          y = 1196,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "marker_a",
          type = "",
          shape = "point",
          x = 100,
          y = 336,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "enemycollision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {

      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {

      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 5,
          name = "savepoint",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text"] = {"* At times,[wait:5] you see it flickering.\n* The light only you can see.", "* By second nature,[wait:5] you reach out,[wait:5] and..."}
          }
        },
        {
          id = 11,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = -10,
          y = 280,
          width = 20.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "room_field_puzzle1",
            ["marker"] = "marker_b",
            ["facing"] = "left"
          }
        },
        {
          id = 12,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 1940,
          y = 1160,
          width = 20.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "room_field_puzzle2",
            ["marker"] = "marker_a",
            ["facing"] = "right"
          }
        },
        {
          id = 15,
          name = "ch1_treasure",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 480,
          width = 80.0,
          height = 80.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "ch1_treasure_room_field_maze_101362"
          }
        },
        {
          id = 16,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_sign",
            ["frames"] = 1,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2,
            ["scale_y"] = 2,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = "* (Behold,[wait:5] the Maze of Death!\n* Prepare to GET LOST,[wait:5] clowns!!!)\n* (SIGNED,[wait:5] LANCER)"
          }
        },
        {
          id = 17,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 860,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_sign",
            ["frames"] = 1,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2,
            ["scale_y"] = 2,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = {"* (Feeling lost yet!? You must be UTTERLY HELPLESS among these twists and turns!)", "* (Your sense of direction won't save you now!)\n* (SIGNED, LANCER)"}
          }
        },
        {
          id = 18,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 680,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_sign",
            ["frames"] = 1,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2,
            ["scale_y"] = 2,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = "* (Hey,[wait:5] wait!! Where am I!? Help! Somebody help! I'm lost!!)\n* (SIGNED,[wait:5] LANCER)"
          }
        },
        {
          id = 19,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 1120,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_sign",
            ["frames"] = 1,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2,
            ["scale_y"] = 2,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = "* (Hey,[wait:5] don't look! This sign's private!)\n* (SIGNED,[wait:5] LANCER)"
          }
        },
        {
          id = 20,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 1080,
          y = 1120,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_sign",
            ["frames"] = 1,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2,
            ["scale_y"] = 2,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = "* (Oh,[wait:5] it's just this way.)\n* (SIGNED,[wait:5] LANCER)"
          }
        },
        {
          id = 32,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 1480,
          y = 1120,
          width = 72.0,
          height = 70.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_lancer_dt",
            ["frames"] = 1,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = "* The Darkner looks at you expectantly."
          }
        },
        {
          id = 73,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 1400,
          y = 700,
          width = 68,
          height = 60,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_puzzlepiece",
            ["frames"] = 2,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2,
            ["scale_y"] = 2,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = "* The Darkner looks at you expectantly."
          }
        },
        {
          id = 74,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 1000,
          y = 360,
          width = 104.0,
          height = 92.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_icemascot_fake",
            ["frames"] = 4,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = "* The Darkner looks at you expectantly."
          }
        },
        {
          id = 75,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 720,
          width = 104.0,
          height = 92.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_icemascot_fake",
            ["frames"] = 4,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = "* The Darkner looks at you expectantly."
          }
        },
        {
          id = 76,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 480,
          width = 104.0,
          height = 92.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_icemascot_fake",
            ["frames"] = 4,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = "* The Darkner looks at you expectantly."
          }
        },
        {
          id = 77,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 1440,
          y = 520,
          width = 104.0,
          height = 92.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_icemascot_fake",
            ["frames"] = 4,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = "* The Darkner looks at you expectantly."
          }
        },
        {
          id = 78,
          name = "ch1_prop",
          type = "",
          shape = "rectangle",
          x = 1240,
          y = 320,
          width = 104.0,
          height = 92.0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["sprite"] = "world/ch1_dark/extracted/spr_npc_icemascot_fake",
            ["frames"] = 4,
            ["start_frame"] = 0,
            ["animation_speed"] = 0,
            ["scale_x"] = 2.0,
            ["scale_y"] = 2.0,
            ["origin_x"] = 0,
            ["origin_y"] = 0,
            ["solid"] = true,
            ["text"] = "* The Darkner looks at you expectantly."
          }
        }
      }
    }
  }
}
